notifications:
  email: false
language: c
addons:
  apt:
    packages:
      - elinks
      - gfortran
      - liblapack3gf

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update             ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc elinks ; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make -C external CC=$CC LAPACK="-L/usr/lib/lapack -llapack"; else make -C external CC=$CC; fi
